name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tree a directory
      run: tree ./
    - name: Zola Deploy to Pages
      uses: shalzz/zola-deploy-action@v0.10.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
